#############################################################################
# Makefile for building: StringEditer
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  StringEditer.pro
# Template: app
# Command: E:\QT_projects\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\bin\qmake.exe -o Makefile StringEditer.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = E:\QT_projects\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: StringEditer.pro ..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\win32-msvc2015\qmake.conf ..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\spec_pre.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\common\angle.conf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\common\msvc-base.conf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\common\msvc-desktop.conf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\qconfig.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dcore.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dextras.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dinput.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dlogic.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquick.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3drender.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3drender_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axbase.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axbase_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axcontainer.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axserver.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axserver_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_bluetooth.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_charts.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_charts_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_clucene_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_concurrent.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_core.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_core_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_datavisualization.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_gamepad.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_gui.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_gui_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_help.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_help_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_location.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_location_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_multimedia.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_network.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_network_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_nfc.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_nfc_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_opengl.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_opengl_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_openglextensions.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_positioning.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_positioning_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_printsupport.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_purchasing.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qml.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qml_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qmltest.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quick.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quick_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_script.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_script_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_scripttools.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_scxml.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_scxml_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_sensors.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_sensors_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_serialbus.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_serialport.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_serialport_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_sql.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_sql_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_svg.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_svg_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_testlib.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_testlib_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_uiplugin.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_uitools.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_uitools_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_webchannel.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_websockets.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_websockets_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_widgets.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_widgets_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_winextras.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_winextras_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_xml.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_xml_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_zlib_private.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_assimpsceneio.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_dsengine.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_gltfsceneio.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qdds.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qgenericbearer.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qicns.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qico.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qminimal.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_debugger.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_inspector.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_local.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_native.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_profiler.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_quickprofiler.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_server.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_tcp.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qnativewifibearer.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qoffscreen.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qsvg.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qsvgicon.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtaudio_windows.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtga.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtgeoservices_mapbox.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtgeoservices_nokia.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtgeoservices_osm.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtiff.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtpeakcanbus.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtposition_positionpoll.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtposition_serialnmea.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtsensors_generic.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qttinycanbus.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtvirtualkeyboardplugin.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qwbmp.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qwebp.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qwindows.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_windowsprintersupport.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_xinputgamepad.pri \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\qt_functions.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\qt_config.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\win32\qt_config.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\win32-msvc2015\qmake.conf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\exclusive_builds.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\toolchain.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\default_pre.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\win32\default_pre.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\resolve_config.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\exclusive_builds_post.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\default_post.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\win32\rtti.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\precompile_header.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\warn_on.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\qt.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\resources.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\moc.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\win32\opengl.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\uic.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\file_copies.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\win32\windows.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\testcase_targets.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\exceptions.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\yacc.prf \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\lex.prf \
		StringEditer.pro \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\lib\qtmain.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\lib\Qt5Widgets.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\lib\Qt5Gui.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\lib\Qt5Core.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\platforms\qwindows.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qdds.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qicns.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qico.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qtga.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qtiff.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qwbmp.prl \
		..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qwebp.prl
	$(QMAKE) -o Makefile StringEditer.pro
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\spec_pre.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\common\angle.conf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\common\msvc-base.conf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\common\msvc-desktop.conf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\qconfig.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dcore.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dcore_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dextras.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dextras_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dinput.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dinput_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dlogic.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquick.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquick_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickextras.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickinput.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickrender.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3drender.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_3drender_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axbase.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axbase_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axcontainer.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axserver.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_axserver_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_bluetooth.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_charts.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_charts_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_clucene_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_concurrent.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_concurrent_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_core.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_core_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_datavisualization.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_gamepad.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_gamepad_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_gui.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_gui_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_help.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_help_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_location.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_location_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_multimedia.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_multimedia_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_network.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_network_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_nfc.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_nfc_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_opengl.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_opengl_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_openglextensions.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_positioning.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_positioning_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_printsupport.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_printsupport_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_purchasing.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_purchasing_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qml.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qml_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qmltest.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qmltest_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quick.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quick_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quickwidgets.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_script.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_script_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_scripttools.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_scripttools_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_scxml.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_scxml_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_sensors.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_sensors_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_serialbus.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_serialbus_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_serialport.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_serialport_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_sql.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_sql_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_svg.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_svg_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_testlib.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_testlib_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_uiplugin.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_uitools.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_uitools_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_webchannel.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_webchannel_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_websockets.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_websockets_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_widgets.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_widgets_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_winextras.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_winextras_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_xml.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_xml_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_lib_zlib_private.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_assimpsceneio.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_dsengine.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_gltfsceneio.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qdds.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qgenericbearer.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qicns.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qico.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qminimal.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_debugger.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_inspector.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_local.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_native.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_profiler.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_quickprofiler.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_server.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qmldbg_tcp.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qoffscreen.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qsvg.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qsvgicon.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtaudio_windows.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtga.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtgeoservices_mapbox.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtgeoservices_nokia.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtgeoservices_osm.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtiff.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtpeakcanbus.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtposition_positionpoll.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtposition_serialnmea.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtsensors_generic.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qttinycanbus.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qtvirtualkeyboardplugin.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qwbmp.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qwebp.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_qwindows.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\modules\qt_plugin_xinputgamepad.pri:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\qt_functions.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\qt_config.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\win32\qt_config.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\win32-msvc2015\qmake.conf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\spec_post.prf:
.qmake.stash:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\exclusive_builds.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\toolchain.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\default_pre.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\win32\default_pre.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\resolve_config.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\exclusive_builds_post.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\default_post.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\win32\rtti.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\precompile_header.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\warn_on.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\qt.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\resources.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\moc.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\win32\opengl.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\uic.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\file_copies.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\win32\windows.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\testcase_targets.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\exceptions.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\yacc.prf:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\mkspecs\features\lex.prf:
StringEditer.pro:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\lib\qtmain.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\lib\Qt5Widgets.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\lib\Qt5Gui.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\lib\Qt5Core.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\platforms\qwindows.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qdds.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qicns.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qico.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qtga.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qtiff.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qwbmp.prl:
..\QT\qt5-5.7.1-vs2015\qt5-x86-static-release\plugins\imageformats\qwebp.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile StringEditer.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) E:\QT_projects\variable-length-string-editor-for-binaries\stringediter_plugin_import.cpp .qmake.stash

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
